name: Docker Build and Push
on:
  push:
    branches:
      - master
jobs:
    build-and-push:
        runs-on: self-hosted
      
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: print
              run: echo "Hello World" 
